spring.application.name=roses-R-rosie
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/roses_ecommerce?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE